### ISSUE TITLE
Virtualenv is not garbage at all

### ISSUE THREAD

**Issue by Asday** [Deepwalker/pundler#30]
Virtualenv is sweet.  It's so sweet I have no idea why people are even bothering with poetry and pipenv and the like.

I think you should try and qualify your assertion in the readme.  If you don't, the only people who will take your package seriously are those who already agree with you.

**Comment by Deepwalker** [comment]
Good note with a lot of arguments. Thank you.
When you read about "garbage" reread twice to get idea please.

**Comment by Asday** [comment]
Fantastic attitude my dude, I'm sure you'll win many people over to your tool.

**Comment by Deepwalker** [comment]
Man, dude, troll.

**Comment by Deepwalker** [comment]
Ok, I changed my mind. Maybe in the end we can get real discussion. I do not believe, but I always can close this issue again.
Did you read this funny thing? https://github.com/Deepwalker/pundler/blob/master/virtualenv.md
Or did you argue without that in mind? I'm all in for good, deep arguing. Your move )

poetry and pipenv are both virtualenv based and in my opinion this is why they are flawed from the ground.

**Comment by Deepwalker** [comment]
And important note – I use this tool for myself. I do not need to win you as user. This is just one more opensource and free tool. I have no any money from you use it too. Keep that in mind ;-)

**Comment by liamdawson** [comment]
You might not need to "win" users. Still, you unconditionally trash the work of others, built to solve problems that were around 12 years ago. You also trash things other people have built merely because they're built on top of that. This sets a really bad precedent of community attitudes. Your points may be entirely valid for particular cases, doesn't mean you're justified to denigrate the work of others.

**Comment by Deepwalker** [comment]
I did not "trash" it, I rant about its way is wrong. Bad to you you can't read funny rants.
